### PR TITLE
Make script executable

### PR DESCRIPTION
**Pull request by jabranr**
Making script executable so that it can run standalone too.

### CODE REVIEW

**Comment by ahmadawais** [comment]
@jabranr what did you change? There's nothing showing up. Script is already executable the way I have instructed it to be installed. 

Looking forward!

**Comment by jabranr** [comment]
@ahmadawais changed the executable mode on file to x using `$ chmod +x ptcli.sh` This is for who want it to run standalone/directly.

**Comment by jabranr** [comment]
[Last line here](https://github.com/ahmadawais/PTCL-CLI/pull/1/commits/292fb8008c525003343286ebfc39581b89856a99) tells you about the changes.

**Review by ahmadawais — CHANGES_REQUESTED** [review]
I am unable to find anything.

**Review by ahmadawais — APPROVED** [review]

**Comment by ahmadawais** [comment]
@jabranr bro, did you read the installation process?

``` bash
sudo wget -qO ptcli https://git.io/vPtPS && sudo chmod +x ./ptcli && sudo install ./ptcli /usr/local/bin/ptcli
```

After running this command everyone ends up with an executable `ptcli` command. How does this PR any different from that? Can you help me understand?

**Comment by jabranr** [comment]
Yes, that's why I have mentioned that it enables using it standalone. What if I don't want to move it to my bin? This just lessens one step on both sides, default installation and using it standalone i.e.

```
cd path/to/ptcli
./ptcli
```

Also you will not need chmod in installation instructions. ;)

**Comment by ahmadawais** [comment]
@jabranr Makes sense. Before I merge this, can you show me how you did it? Since I have no way of finding out what's changed.

**Comment by jabranr** [comment]
I simply forked the repository and ran `$ chmod +x ptcli.sh` to make it executable. ;)

**Comment by jabranr** [comment]
Sorry closed the PR but realised that it is not yet merged so reopened it.

**Comment by ahmadawais** [comment]
@jabranr This permission should be run in the Users' OS. It cannot be copied over to another OS. Which is why, it is necessary to run `chmod +x ptcli.sh` in the install.

**Comment by jabranr** [comment]
I doubt that a file mode cannot be copied. At work we have a lot of scripts that are copied to different OSs just fine. However there is a possibility that another hook at user side may override this mode but that's an edge case.

**Pull request merged**
